### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [wendal/alipay-sdk#1]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 122: API name => IvParameterSpec:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 97: API name => SecretKeySpec:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 603: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[])>, <javax.crypto.Cipher: byte[] doFinal(byte[])>, <javax.crypto.Cipher: int doFinal(java.nio.ByteBuffer,java.nio.ByteBuffer)>, update, <javax.crypto.Cipher: byte[] doFinal(byte[],int,int)>, <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[],int)><BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 94: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 100: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 126: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 100: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 618: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 121: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 337: API name => Signature:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 303: API name => Signature:First parameter (with value "SHA256WithRSA") should be any of {NONEwithDSA, SHA1withDSA, SHA224withDSA, SHA256withDSA, SHA256withRSA, SHA256withECDSA}<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 558: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to update, doFinal<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 123: API name => SecretKeySpec:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 313: API name => Signature:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 137: API name => Signature:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 172: API name => Signature:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 162: API name => Signature:First parameter (with value "SHA1WithRSA") should be any of {NONEwithDSA, SHA1withDSA, SHA224withDSA, SHA256withDSA, SHA256withRSA, SHA256withECDSA}<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 127: API name => Signature:First parameter (with value "SHA256WithRSA") should be any of {NONEwithDSA, SHA1withDSA, SHA224withDSA, SHA256withDSA, SHA256withRSA, SHA256withECDSA}<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 572: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 144: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to init<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 570: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 570: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 98: API name => SecretKeySpec:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 123: API name => SecretKeySpec:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 327: API name => Signature:First parameter (with value "SHA1WithRSA") should be any of {NONEwithDSA, SHA1withDSA, SHA224withDSA, SHA256withDSA, SHA256withRSA, SHA256withECDSA}<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 616: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 618: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 616: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipaySignature.java: Line number => 572: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 96: API name => IvParameterSpec:<BR> File name => src/main/java/com/alipay/api/internal/util/AlipayEncrypt.java: Line number => 126: API name => Cipher:<BR> File name => src/main/java/com/alipay/api/internal/util/AtsUtils.java: Line number => 182: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR>

**Comment by wendal** [comment]
pls use https://github.com/alipay/alipay-sdk-java-all
